#!/usr/bin/env bash

SINK="@DEFAULT_SINK@"
STEP="${2:-0.05}"

case "$1" in
  up)
    wpctl set-mute "$SINK" 0
    wpctl set-volume -l 1.0 "$SINK" "${STEP}+"
    ;;
  down)
    wpctl set-mute "$SINK" 0
    wpctl set-volume "$SINK" "${STEP}-"
    ;;
  mute)
    wpctl set-mute "$SINK" toggle
    ;;
  *)
    echo "Usage: volume.sh up|down|mute [step]"
    exit 1
    ;;
esac

volume=$(wpctl get-volume "$SINK")
vol_value=$(echo "$volume" | awk '{print $2 * 100}')
vol_status=$(echo "$volume" | cut -d" " -f3)

if [ "$vol_status" = "[MUTED]" ]; then
  notify-send -a muted -h int:value:"0" " "

  exit 0
fi

notify-send -a volume -h int:value:"$vol_value" " "
