###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use

# Terminal
$terminal = kitty

# File mananger
$fileManager = dolphin

# Menu
$rofi_app = ~/.config/rofi/scripts/appdrawer
$rofi_power = ~/.config/rofi/scripts/powermenu
$rofi_bg = ~/.config/rofi/scripts/bgselector

