###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use

# Terminal
$terminal = kitty

# File mananger
$fileManager = dolphin

# Menu
$rofi_app = ~/.config/hypr/scripts/appdrawer
$rofi_power = ~/.config/hypr/scripts/powermenu
$rofi_bg = ~/.config/hypr/scripts/bgselector

# Volume
$volume = ~/.config/hypr/scripts/volumeosd

# Brightness
$brightness = ~/.config/hypr/scripts/brightness

