#!/usr/bin/env bash

shutdown="󰐥"   # power
reboot="󰜉"     # restart
suspend="󰒲"    # sleep
logout="󰗽"     # logout

chosen="$(printf "%s\n%s\n%s\n%s\n" "$shutdown" "$reboot" "$suspend" "$logout" \
    | rofi -dmenu -config "$HOME/.config/rofi/powermenu.rasi")"

case "$chosen" in
  "$shutdown")
    poweroff
    ;;
  "$reboot")
    reboot
    ;;
  "$suspend")
    systemctl suspend
    ;;
  "$logout")
    hyprctl dispatch 'hl.dsp.exit()'
    ;;
  *)
    exit 0
    ;;
esac
